### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'owner_id'

### ISSUE THREAD

**Issue by sevrino** [BotExamples/dmbot#3]
`Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "run.py", line 8, in on_message
    async def on_message(message): await bot.use_cmd(message)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chdp\client.py", line 161, in use_cmd
    await run(m)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chdp\client.py", line 135, in run
    r = self.check_permissions(message.author, c.user_per)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chdp\client.py", line 168, in check_permissions
    if not self.check_permission(author, p): return False
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chdp\client.py", line 172, in check_permission
    memper = author.guild_permissions
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\member.py", line 453, in guild_permissions
    if self.guild.owner_id == self.id:
AttributeError: 'NoneType' object has no attribute 'owner_id'`

위와 같이 오류가 발생하여 문의드립니다.

**Comment by kiki7000** [comment]
discord.py 문제입니다
